module.exports = {
  projects: [
    '<rootDir>/apps/application-b2b',
    '<rootDir>/apps/application-b2c',
    '<rootDir>/libs/shared/ui',
    '<rootDir>/libs/shared/data-models',
    '<rootDir>/libs/shared/identity-b2b',
    '<rootDir>/libs/shared/identity-b2c',
    '<rootDir>/libs/shared/services',
    '<rootDir>/libs/application-b2b/dashboard',
    '<rootDir>/libs/application-b2c/dashboard',
    '<rootDir>/libs/application-b2b/home',
    '<rootDir>/libs/application-b2c/home',
    '<rootDir>/libs/shared/application/services',
    '<rootDir>/libs/shared/application/types',
    '<rootDir>/libs/shared/application/state/students-state',
    '<rootDir>/libs/shared/application/state/courses-state',
    '<rootDir>/libs/shared/application/state/instructors-state',
    '<rootDir>/libs/shared/application/state/parents-state',
    '<rootDir>/libs/shared/app-config',
    '<rootDir>/libs/shared/framework/storage',
  ],
};
